env:
  browser: true
  es6: true
  node: true

extends:
  - eslint-config-nestjs

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: './tsconfig.json'

plugins:
  - import
  - node
  - prettier
  - '@typescript-eslint'
  - unused-imports

rules:
  prettier/prettier: error
  unused-imports/no-unused-imports:
    - error
  import/order:
    - error
    - groups:
        - builtin # Built-in Node.js modules like fs, path, etc.
        - external # Packages from node_modules
        - internal # Internal paths (alias paths)
        - parent # Parent folders
        - sibling # Sibling files/folders
        - index # Index files
        - object # Object imports
      newlines-between: always
