name: Build & Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy_to_droplet:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Deploy to Droplet
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USERNAME_PROD }}
          key: ${{ secrets.SSH_KEY_PROD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd "${{secrets.PRODUCTION_FOLDER}}"
            git pull origin main
            echo "${{ secrets.DOT_ENV_PRODUCTION }}" > .env
            docker system prune --force
            docker-compose -f docker-compose-prod.yml stop microservicio_ryp_api
            docker rm -f microservicio_ryp
            docker-compose -f docker-compose-prod.yml build microservicio_ryp_api
            docker-compose -f docker-compose-prod.yml up -d microservicio_ryp_api
            exit
